SFTP - Allow IP's & Users

diff --git a/files/entrypoint b/files/entrypoint
--- a/files/entrypoint
+++ b/files/entrypoint
@@ -12,6 +12,19 @@ userConfPath="/etc/sftp/users.conf"
 userConfPathLegacy="/etc/sftp-users.conf"
 userConfFinalPath="/var/run/sftp/users.conf"
 
+echo 'PermitEmptyPasswords no' >> /etc/ssh/sshd_config
+echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config
+
+if [ -z "$SFTP_ALLOWED_IPS" ] && [ -z "$SFTP_ALLOWED_USERS" ]; then
+    log "ERROR:  Please set up SFTP_ALLOWED_IPS & SFTP_ALLOWED_USERS values in Environment"   
+    exit 3
+else 
+    echo "Match Address ${SFTP_ALLOWED_IPS}" >> /etc/ssh/sshd_config   
+    echo '       PasswordAuthentication yes' >> /etc/ssh/sshd_config
+    echo "       AllowUsers ${SFTP_ALLOWED_USERS}" >> /etc/ssh/sshd_config
+    echo "INFO: Allowed IP's: ${SFTP_ALLOWED_IPS} & Allowed Users:${SFTP_ALLOWED_USERS} are Set"
+fi
+
 function log() {
     echo "[$0] $*" >&2
 }
